const nouns = [
    "Synergy",
    "Data",
    "Growth",
    "Solution",
    "Industry",
    "Leaders",
    "Suite",
    "Offerings",
    "Value",
    "Paradigm shifts",
    "Verticals",
    "Standard setters",
    "Blockchains",
    "User experience",
    "Diversities",
    "Architecture",
    "Dot-bombs",
    "Enterprise space",
    "Imaginings",
    "Standpoint space",
    "Intrapreneurs",
    "Digital nomads",
    "Bandwidths",
    "Clouds",
    "Alignments",
    "Stand-ups",
    "Business",
    "NFTs",
    "Innovation",
    "Ownership",
    "Digital nomads",
    "Stakeholders",
    "Wholesale senior bandwidths",
    "End-to-end siloes",
    "Ballpark figures",
    "Capabilities",
    "Prince2 practitioners",
    "Propositions",
    "Capability",
    "Game changer",
    "Driver",
    "Best practices",
    "Creator",
    "Platform",
    "Executive searches",
    "Low hanging fruit",
    "Core assets",
    "Deliverable velocity",
    "Brands",
    "Culture",
    "Lifecycle",
    "Visibility",
    "Market foci",
    "Proactive Platform",
    "Action points",
    "Smart contracts",
    "Workflows",
    "Knowledge transfer",
    "Intrapreneurs",
    "Bandwidth",]


export default nouns;