export const subject = [
    "Artificial Intelligence",
    "Machine Learning",
    "Big Data",
    "Cloud Computing",
    "Internet of Things",
    "Blockchain",
    "Augmented Reality",
    "Virtual Reality",
    "Cybersecurity",
    "Data Science",
    "Deep Learning",
    "Quantum Computing",
    "Automation",
    "Cryptocurrency",
    "Edge Computing",
    "Chatbots",
    "DevOps",
    "Agile",
    "Robotics",
    "5G",
    "Neural Networks",
    "Natural Language Processing",
    "API",
    "SaaS",
    "PaaS",
    "IaaS",
    "Microservices",
    "Containers",
    "Docker",
    "Kubernetes",
    "Serverless",
    "IoT Platform",
    "Smart Home",
    "Wearable Technology",
    "Biometrics",
    "Cloud Native",
    "Hybrid Cloud",
    "Data Analytics",
    "Predictive Analytics",
    "Internet Security",
    "Mobile App Development",
    "User Experience",
    "User Interface",
    "Gamification",
    "E-commerce",
    "Digital Transformation",
    "Robotic Process Automation",
    "Edge Computing",
    "Data Visualization",
    "Growth Hacking",
    "API Economy",
    "Continuous Integration",
    "Continuous Deployment",
    "Low-Code Development",
    "No-Code Development",
    "Cyber Threat Intelligence",
    "Network Security",
    "Cloud Storage",
    "Edge Devices",
    "Natural Language Generation",
    "Machine Vision",
    "Predictive Maintenance",
    "Serverless Architecture",
    "Agile Development",
    "Business Intelligence",
    "Neural Networks",
    "Data Mining",
    "Data Warehousing",
    "Digital Twin",
    "Fog Computing",
    "Edge Analytics",
    "Digital Disruption",
    "Agile Project Management",
    "Internet Privacy",
    "Software Development Lifecycle",
    "Quantum Cryptography",
    "Cloud-Native Applications",
    "Software Defined Networking",
    "Edge Intelligence",
    "Data Privacy",
    "Multi-Cloud",
    "Cyber Resilience",
    "Cloud-Native Development",
    "Voice Recognition",
    "Augmented Analytics",
    "Internet of Medical Things",
    "Web Services",
    "API Integration",
    "Cyber Threat Hunting",
    "Data Engineering",
    "IoT Security",
    "Social Media Analytics",
    "Mobile Device Management",
    "Cloud-Native Infrastructure",
    "Digital Ethics",
    "Natural Language Understanding",
    "Data Governance",
    "Predictive Modeling",
    "Cloud Migration",
    "IT Service Management",
]